### ISSUE TITLE
Error DOMException: Failed to execute 'setEnd' on 'Range': The offset 45 is larger than the node's length (44).

### ISSUE THREAD

**Issue by ividyon** [niklasvh/html2canvas#1325]
* html2canvas version tested with: 1.0.0-alpha.4
* Browser & version: Google Chrome 63.0.3239.84 64-bit
* Operating system: Windows 10

```
Error DOMException: Failed to execute 'setEnd' on 'Range': The offset 45 is larger than the node's length (44).
    at getRangeBounds (http://my-local-site.test/libraries/html2canvas/dist/html2canvas.js?v=1.0.0-alpha.4:2310:11)
    at parseTextBounds (http://my-local-site.test/libraries/html2canvas/dist/html2canvas.js?v=1.0.0-alpha.4:2278:54)
    at Function.fromTextNode (http://my-local-site.test/libraries/html2canvas/dist/html2canvas.js?v=1.0.0-alpha.4:1640:84)
    at parseNodeTree (http://my-local-site.test/libraries/html2canvas/dist/html2canvas.js?v=1.0.0-alpha.4:2887:64)
    at parseNodeTree (http://my-local-site.test/libraries/html2canvas/dist/html2canvas.js?v=1.0.0-alpha.4:2918:29)
```

Happens when trying to run the script.

**Comment by niklasvh** [comment]
Please share example on jsfiddle

**Comment by ividyon** [comment]
I can't really share an example since it's from a full-featured site, and a private feature on that (connected to our internal ticket system). Is there any specific info I can provide?

**Comment by niklasvh** [comment]
@ividyon I would need a way to replicate the issue somehow to be able to find a solution for this. What kind of text do you have on there (is it english/latin, or something else?) Do you have any weird unicodes?

**Comment by balgopal14** [comment]
same error for me, i'm using this with jsPdf for generating pdf. It working fine but on some pdf creation it shows this error ------
DOMException: Failed to execute 'setEnd' on 'Range': The offset 59 is larger than the node's length (58).

**Comment by balgopal14** [comment]
I found the root cause of this error, if any special character like ('ß') present in your text and its Unicode html conversion is 'ss' that's increase the length of offset. Please update the library
Thanks.

**Comment by ManukMinasyan** [comment]
Hello dear developers, I have the same issue, how I can fix it? Thanks

**Comment by pourashraf** [comment]
> I found the root cause of this error, if any special character like ('ß') present in your text and its Unicode html conversion is 'ss' that's increase the length of offset. Please update the library
> Thanks.

Hi, this is my issue now. Is there any solution you know in the meanwhile?

**Comment by balgopal14** [comment]
> > I found the root cause of this error, if any special character like ('ß') present in your text and its Unicode html conversion is 'ss' that's increase the length of offset. Please update the library
> > Thanks.
> 
> Hi, I'm facing this issue now. Is there any solution you know in the meanwhile?

Hi, For me this issues was fixed when I updated the library, Please try it.

**Comment by pourashraf** [comment]
> > > I found the root cause of this error, if any special character like ('ß') present in your text and its Unicode html conversion is 'ss' that's increase the length of offset. Please update the library
> > > Thanks.
> > 
> > 
> > Hi, I'm facing this issue now. Is there any solution you know in the meanwhile?
> 
> Hi, For me this issues was fixed when I updated the library, Please try it.

I upgraded html2canvas lib to the l;atest version 1.0.0-rc.7. But the issue's still there :(

**Comment by Kimmax** [comment]
Same in 1.1.4. Can confirm what @balgopal14 said.

**Comment by AignerTom** [comment]
Currently running version 1.4.0 but I am still getting this error. Are there any news on this ? @ividyon

**Comment by elvomka** [comment]
The special character `ß` will be rendered as `SS` if you have a `text-transform: uppercase;` and this will trick html2canvas. I solved it by replacing `ß` by `SS` in the markup, when I knew the text would be rendered in uppercase.

**Comment by healqq** [comment]
Adding on previous answer - I would suggest to use String.toLocaleUpperCase (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleUpperCase) to do that replacement automatically.

**Comment by milo526** [comment]
Issue still present in v1.4.1

Reproduction:

https://jsfiddle.net/skng7taq/21/

Please observe how the last (upper-cased) entry does not get rendered and see the error in your console.

**Comment by balgopal14** [comment]
@milo526 the issue is related to ẞ (uppercase) and ß (lowercase).
In your JS fiddle if you just change the last (upper-cased) entry to this **ß** it will work.

**Comment by Tlepel** [comment]
@balgopal14 In the JS fiddle that @milo526 sent the last entry already has a lowercase ß in the html, which is transformed using `text-transform: uppercase;`. Changing the character to an uppercase ẞ makes the error go away, but that isn't a proper solution to the problem, rather it's a workaround.
