### ISSUE TITLE
Cannot read property 'logging' of undefined

### ISSUE THREAD

**Issue by csbenjamin** [niklasvh/html2canvas#543]
The log module uses window.html2canvas.logging and window.html2canvas is undefined because I'm using html2canvas inside requirejs

**Comment by usmonster** [comment]
Will probably be resolved with #528. Might want to follow that issue (and close this one?).

**Comment by legomushroom** [comment]
Hey guys!
Having the same issue with **webpack** and html2canvas **0.5.0-alpha2**.
Any thoughts?

**Comment by usmonster** [comment]
@legomushroom my guess is it's the same issue.

**Comment by hustcltuch** [comment]
i have the same issue as @legomushroom , and i solved it by add html2canvas into window like this:

window.html2canvas = html2canvas;
        html2canvas.default(document.body, {
            onrendered: function(canvas){
                var canvasImg = canvas.toDataURL("image/jpg");

**Comment by jdfreder** [comment]
I can verify that this is still a problem when loading with AMD
